<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://drive.google.com/file/d/1GV5gEXg7e8BycgaGZEU2sL_fVQlmb6C_/view" alt="C10ud4o4">
                        <h6>Vincent Derrick</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                          <li><a href="https://twitter.com/ihamquentin" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ihamquentin" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@vincentderrick555" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>skilled and result-oriented software developer, had a few years of practice and still gathring experience, worked with a few developement environment and i have a learn more attitude to everything</p>
                        <br />
                        <h6>Skills</h6>
                        <p>c++ | PHP | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
